services:
  mysql:
    container_name: mysql-s1
    platform: linux/x86_64
    build: ./mysql/
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=archmage
      - MYSQL_DATABASE=fastapi_app
    tty: true
  backend:
    depends_on:
      - mysql
    build: ./backend
    container_name: backend-fastapi-mysql-api
    command: [
      "uvicorn",
      "main:app",
      "--host", "0.0.0.0",
      "--port", "5000",
      "--reload",
      "--reload-include", "*"
    ]
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    environment:
      - APP_SECRET_STRING=archmage
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=archmage
      - DATABASE=fastapi_app
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
  frontend:
    build: ./frontend
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - 80:8080